version: "3"

services:

    backend:
        build: ./backend
        expose:
            - "8080"
        environment:
            - APP_CONFIG=${APP_CONFIG}
            - TZ=PRC
        volumes:
            - ./gxblog_app:/gxblog_app
        depends_on:
            - ethnode
            - mysql
        command: ./wsgi.py

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            # - ./frontend:/usr/share/nginx/html/frontend
            - ./frontend/dist:/gxblog
            - ./backend/app/static:/gxblog/resource/static
        depends_on:
            - backend

    ethnode:
        image: ethereum/client-go
        ports:
            - "8545:8545"
            - "30303:30303"
        volumes:
            - /Users/wuyi/Library/Ethereum/:/root
        command: "--testnet --rpc --rpcaddr 0.0.0.0 --syncmode light"

    mysql:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql/data:/var/lib/mysql
        environment:
            - TZ=PRC
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
