version: "3"

services:

    backend:
        build: ./backend
        expose:
            - "8000"
        network_mode: "host"
        env_file: .env
        environment:
            - TZ=PRC
        volumes:
            - ./gxblog_app:/gxblog_app
              #         depends_on:
              #             - mysql
              #             - redis
        command: ./wsgi.py

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./frontend/dist:/gxblog
            - ./backend/app/static:/gxblog/resource/static
        depends_on:
            - backend

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - TZ=PRC
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ./data/mysql:/var/lib/mysql

    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis/data:/data
        command: ["redis-server", "--appendonly", "yes"]
