version: "3"

services:

    backend:
        build: ./backend
        expose:
            - "8000"
        env_file: .env
        environment:
            - TZ=PRC
        volumes:
            - ./gxblog_app:/gxblog_app
        depends_on:
            - ethnode
            - mysql
            - redis
        command: ./wsgi.py

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./frontend/dist:/gxblog
            - ./backend/app/static:/gxblog/resource/static
        depends_on:
            - backend

    ethnode:
        image: ethereum/client-go
        ports:
            - "8545:8545"
            - "30303:30303"
        environment:
            - ETH_MODE=${ETH_MODE}
            - TZ=PRC
        volumes:
            - ./data/ethereum/ropsten:/root/ropsten
            - ./data/ethereum/private:/root/private
            - ./genesis.json:/root/genesis.json
            - ./run_eth.sh:/root/run_eth.sh
        # command: bash /root/run_eth.sh
        # command: "--datadir /root/dev --testnet --syncmode light --rpc --rpcaddr 0.0.0.0 --rpccorsdomain * --rpcapi eth,net,web3,personal"
        command: "--datadir /root/private/data --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3,personal,miner"

    mysql:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        environment:
            - TZ=PRC
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ./data/mysql:/var/lib/mysql

    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis/data:/data
        command: ["redis-server", "--appendonly", "yes"]
